"""Generate the vendored device-catalog snapshot from a catalog checkout.

Run from the repo root:

    python3 scripts/generate_catalog_snapshot.py [catalog_path] \
        [--commit SHA] [--date YYYY-MM-DD]

``catalog_path`` defaults to ``../indigo-device-catalog`` (a sibling
checkout of https://github.com/simons-plugins/indigo-device-catalog).
Output is written to ``Server Plugin/catalog_snapshot.py`` — a plain
Python data table, same vendored-data pattern as ``xkcd_palette.py``:
no runtime file I/O, no network, importable stdlib-only.

``--commit`` and ``--date`` stamp SNAPSHOT_META. When omitted they are
derived from the catalog checkout's git HEAD (commit sha + committer
date) — a function of the checkout, never of the wall clock, so the
output is deterministic: the same catalog commit always produces a
byte-identical snapshot.

Only fields the profile schema actually carries are vendored:
``capabilities`` (boolean flag map), ``base_class``, ``protocol``,
``model``, ``sub_model``, and ``display_state_id``. Per-profile
``states`` are deliberately dropped — the live device's states are
already returned by ``get_device_by_id`` and are strictly fresher.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CATALOG = REPO_ROOT.parent / "indigo-device-catalog"
OUTPUT_PATH = (
    REPO_ROOT / "Indigo MCP Lite.indigoPlugin" / "Contents"
    / "Server Plugin" / "catalog_snapshot.py"
)

# Optional profile fields carried into the snapshot, as
# (snapshot_key, catalog_key) pairs. Absent/empty values are omitted
# per profile so the vendored file stays lean.
_OPTIONAL_FIELDS = (
    ("protocol", "protocol"),
    ("model", "model"),
    ("sub_model", "subModel"),
    ("display_state_id", "displayStateId"),
)


def _git_meta(catalog_path):
    """Best-effort (commit, date) from the catalog checkout's git HEAD.

    Returns ("unknown", "unknown") if the path isn't a git checkout or
    git isn't available — the snapshot is still generated, just without
    provenance. Deliberately never reads the wall clock.
    """
    def _run(*args):
        return subprocess.run(
            ["git", "-C", str(catalog_path), *args],
            capture_output=True, text=True, check=True,
        ).stdout.strip()

    try:
        # --date=short + %cd rather than %cs: %cs is unsupported on
        # older gits and degrades to the literal string "%cs".
        return (
            _run("rev-parse", "HEAD"),
            _run("log", "-1", "--format=%cd", "--date=short"),
        )
    except (OSError, subprocess.CalledProcessError):
        return "unknown", "unknown"


def build_profiles(catalog_path):
    """Read every by-class JSON file into {(pluginId, deviceTypeId): profile}.

    Raises ValueError (not a bare crash) on a missing catalog dir or a
    duplicate key so the CI workflow fails with a message a human can
    act on.
    """
    by_class = Path(catalog_path) / "catalog" / "by-class"
    if not by_class.is_dir():
        raise ValueError(
            f"no catalog/by-class directory under {catalog_path} — "
            "pass the root of an indigo-device-catalog checkout"
        )
    profiles = {}
    for class_file in sorted(by_class.glob("*.json")):
        data = json.loads(class_file.read_text())
        base_class = data.get("baseClass", "")
        for profile in data.get("profiles", []):
            key = (profile["pluginId"], profile["deviceTypeId"])
            if key in profiles:
                raise ValueError(
                    f"duplicate catalog key {key} (second occurrence in "
                    f"{class_file.name}) — fix the catalog before regenerating"
                )
            entry = {
                "base_class": base_class,
                # Sorted so the emitted repr is deterministic.
                "capabilities": {
                    k: bool(v)
                    for k, v in sorted(profile.get("capabilities", {}).items())
                },
            }
            for snap_key, cat_key in _OPTIONAL_FIELDS:
                value = profile.get(cat_key)
                if value:
                    entry[snap_key] = value
            profiles[key] = entry
    return profiles


def render(profiles, commit, date):
    """Render the snapshot module source as a string (deterministic)."""
    lines = [
        '"""Vendored snapshot of the indigo-device-catalog profiles.',
        "",
        "AUTO-GENERATED by scripts/generate_catalog_snapshot.py — do not",
        "edit by hand; regenerate from a catalog checkout instead. Same",
        "vendored-data pattern as ``xkcd_palette.py``: plain dicts, no",
        "runtime I/O, no network.",
        "",
        "``PROFILES`` maps ``(pluginId, deviceTypeId)`` to a profile dict",
        "carrying the capability flag map plus base class / protocol /",
        "model metadata. ``catalog.profile_for`` is the lookup helper.",
        '"""',
        "",
        "",
        "SNAPSHOT_META = {",
        f"    \"catalog_commit\": {commit!r},",
        f"    \"catalog_date\": {date!r},",
        f"    \"profile_count\": {len(profiles)},",
        "}",
        "",
        "",
        "PROFILES = {",
    ]
    for key in sorted(profiles):
        lines.append(f"    {key!r}: {profiles[key]!r},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Vendor a device-catalog snapshot into the plugin."
    )
    parser.add_argument(
        "catalog_path", nargs="?", default=str(DEFAULT_CATALOG),
        help="path to an indigo-device-catalog checkout "
             "(default: ../indigo-device-catalog)",
    )
    parser.add_argument(
        "--commit", help="catalog commit sha for SNAPSHOT_META "
                         "(default: derived from the checkout's git HEAD)",
    )
    parser.add_argument(
        "--date", help="catalog commit date (YYYY-MM-DD) for SNAPSHOT_META "
                       "(default: derived from the checkout's git HEAD)",
    )
    parser.add_argument(
        "--output", default=str(OUTPUT_PATH),
        help="output path (default: Server Plugin/catalog_snapshot.py)",
    )
    args = parser.parse_args(argv)

    profiles = build_profiles(args.catalog_path)
    commit, date = args.commit, args.date
    if commit is None or date is None:
        git_commit, git_date = _git_meta(args.catalog_path)
        commit = commit if commit is not None else git_commit
        date = date if date is not None else git_date

    source = render(profiles, commit, date)
    Path(args.output).write_text(source)
    print(f"wrote {args.output}: {len(profiles)} profiles "
          f"(catalog {commit[:12]} {date})")


if __name__ == "__main__":
    try:
        main()
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
