"""Generate the README's tool-list table from the live registry.

Run from the repo root:

    /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 \
        scripts/generate_tool_doc.py

Output is written to stdout as Markdown. The README keeps a copy in
the body between ``<!-- BEGIN TOOL TABLE -->`` and
``<!-- END TOOL TABLE -->`` markers; refresh by piping through
``sed`` or by running this script and pasting.

Single source of truth is ``tool_registry.register_all`` — the
script imports the same registration path the live plugin uses, so
new tools added to any ``tools/*.py`` module automatically show up
in the table on the next regenerate.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from unittest.mock import MagicMock


REPO_ROOT = Path(__file__).resolve().parent.parent
SERVER_PLUGIN = (
    REPO_ROOT / "Indigo MCP Lite.indigoPlugin" / "Contents" / "Server Plugin"
)
sys.path.insert(0, str(SERVER_PLUGIN))


def _build_handler():
    """Construct an MCPHandler with all tools registered.

    Uses MagicMock for the indigo runtime + a no-op Indexer so we
    can call ``tool_registry.register_all`` exactly the way the live
    plugin does, without needing a running Indigo server. The
    handler ends up with the full real registration record for
    every tool (name, description, schema).
    """
    sys.modules.setdefault("indigo", MagicMock(name="indigo"))
    from indexer import Indexer
    from mcp_handler import MCPHandler
    from tool_registry import register_all

    indigo_mock = MagicMock(name="indigo")
    indigo_mock.devices = []
    indigo_mock.variables = []
    indigo_mock.actionGroups = []

    indexer = Indexer(indigo_module=indigo_mock)
    indexer.build()

    handler = MCPHandler(server_name="indigo-mcp-lite", server_version="docgen")
    register_all(handler, indigo_module=indigo_mock, indexer=indexer)
    return handler


# System tool names are checked first so plugin-related tools don't
# leak into the generic Lookup bucket via the ``list_*``/``get_*``
# prefix rules.
_SYSTEM_TOOLS = frozenset({
    "query_event_log", "list_plugins", "get_plugin_by_id",
    "get_plugin_status", "restart_plugin",
})


# Automation-contents tools (.indiDb reader) get their own group;
# without this, find_automation_references would match no predicate
# and silently vanish from the table.
_AUTOMATION_CONTENT_TOOLS = frozenset({
    "get_automation_contents", "find_automation_references",
    "list_automation_scripts",
})


def _is_lookup(n):
    if n in _SYSTEM_TOOLS or n in _AUTOMATION_CONTENT_TOOLS:
        return False
    return n.startswith("list_") or n.startswith("get_")


def _is_control(n):
    return (
        n.startswith("device_") or n.startswith("thermostat_")
        or n.startswith("variable_") or n == "action_execute_group"
    )


_GROUPS = (
    ("Lookup", _is_lookup),
    ("Automation contents", lambda n: n in _AUTOMATION_CONTENT_TOOLS),
    ("Control", _is_control),
    ("System", lambda n: n in _SYSTEM_TOOLS),
    ("Search", lambda n: n == "find_devices"),
)


def _row(name, description):
    """Render one Markdown table row, single-line and pipe-escaped."""
    one_line = " ".join(description.split())
    safe = one_line.replace("|", "\\|")
    return f"| `{name}` | {safe} |"


def main():
    handler = _build_handler()
    # _tools is {name: {description, inputSchema, handler}} — flatten
    # to (name, description) pairs sorted alphabetically for stable diffs.
    tools = sorted(
        (name, info["description"])
        for name, info in handler._tools.items()  # type: ignore[attr-defined]
    )

    print(f"<!-- AUTO-GENERATED by scripts/generate_tool_doc.py — "
          f"{len(tools)} tools -->")
    print()

    for label, predicate in _GROUPS:
        group = [(name, desc) for name, desc in tools if predicate(name)]
        if not group:
            continue
        print(f"### {label} tools ({len(group)})")
        print()
        print("| Tool | Description |")
        print("|------|-------------|")
        for name, desc in group:
            print(_row(name, desc))
        print()


if __name__ == "__main__":
    main()
